services:
  mongo_db:
    image: mongo:8.0.5
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGODB_USER }}
      - MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGODB_PASSWORD }}
    ports:
      - ${{ secrets.MONGODB_LOCAL_PORT }}:${{ secrets.MONGODB_DOCKER_PORT }}
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongo_db
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - ${{ secrets.SPRING_LOCAL_PORT }}:${{ secrets.SPRING_DOCKER_PORT }}
    environment: 
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_PASSWORD }}@mongo_db:${{ secrets.MONGODB_DOCKER_PORT }}/${{ secrets.MONGODB_DATABASE }}?authSource=admin"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
